spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final_java
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: caoquan415@gmail.com
    password: 'nqikttveiykmrfdn'  # App-Password 16 ký tự, không dấu cách
    from: caoquan415@gmail.com    # sẽ dùng làm MAIL FROM:<...>
    default-encoding: UTF-8       # ← phải nằm ở đây, bên dưới spring.mail
    properties:
      # Các property dưới đây map trực tiếp vào JavaMailSenderImpl
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.from: caoquan415@gmail.com
      mail.debug: true
